wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: epoch
      6:
      - 3
    - 1: lr
      5: 1
      6:
      - 1
      - 3
    - 1: epoch_loss_train
      5: 1
      6:
      - 1
      - 3
    - 1: epoch_top1_train
      5: 1
      6:
      - 1
      - 3
    - 1: epoch_top5_train
      5: 1
      6:
      - 1
      - 3
    - 1: epoch_timings
      5: 1
      6:
      - 1
      - 3
    - 1: epoch_top1_val
      5: 1
      6:
      - 1
      - 3
    - 1: epoch_top5_val
      5: 1
      6:
      - 1
      - 3
    python_version: 3.8.2
    start_time: 1636997182
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 7
      4: 3.8.2
      5: 0.12.1
      8:
      - 5
dataset_name:
  desc: null
  value: flower102
entity:
  desc: null
  value: sgirish
init_lr:
  desc: null
  value: 5.0
kfolds:
  desc: null
  value: 3
lr_schedule_type:
  desc: null
  value: cosine
manual_seed:
  desc: null
  value: null
momentum:
  desc: null
  value: 0.9
n_epochs:
  desc: null
  value: 100
n_worker:
  desc: null
  value: 1
no_nesterov:
  desc: null
  value: false
opt_type:
  desc: null
  value: sgd
path:
  desc: null
  value: /fs/vulcan-projects/gan_wild_ss/nas_ssl/logdir/eval_linear_inat21-lr5.0_inat21-resnet50/features_flower102.pt
project_name:
  desc: null
  value: vulcan_runs
resume:
  desc: null
  value: false
run_name:
  desc: null
  value: wd0.0_lr5.0_bs128_flower102
test_batch_size:
  desc: null
  value: 500
train_batch_size:
  desc: null
  value: 128
use_svm:
  desc: null
  value: false
use_wandb:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0.0
